const $=id=>document.getElementById(id);
const url=$('url'),find=$('find'),scanner=$('scanner'),results=$('results'),bar=$('bar'),pct=$('pct'),toast=$('toast');
function msg(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),2400)}
function platform(v){v=v.toLowerCase();if(v.includes('tiktok.com'))return'TikTok';if(v.includes('instagram.com'))return'Instagram';if(v.includes('youtube.com')||v.includes('youtu.be'))return'YouTube';if(v.includes('facebook.com')||v.includes('fb.watch'))return'Facebook';if(v.includes('x.com')||v.includes('twitter.com'))return'X';return'Social Media'}
function valid(v){try{return['http:','https:'].includes(new URL(v).protocol)}catch{return false}}
function steps(n){for(let i=1;i<=4;i++){let e=$('s'+i);e.classList.toggle('active',i<=n)}}
find.onclick=()=>{let v=url.value.trim();if(!v)return msg('Tempel link video terlebih dahulu.');if(!valid(v))return msg('Format link belum valid.');find.disabled=true;find.textContent='Menganalisis...';scanner.classList.remove('hidden');results.classList.add('hidden');let p=0;steps(1);bar.style.width='0%';pct.textContent='0%';scanner.scrollIntoView({behavior:'smooth',block:'center'});let timer=setInterval(()=>{p=Math.min(100,p+Math.floor(Math.random()*9)+6);bar.style.width=p+'%';pct.textContent=p+'%';if(p>=25)steps(1);if(p>=48)steps(2);if(p>=72)steps(3);if(p>=90)steps(4);if(p===100){clearInterval(timer);setTimeout(()=>show(v),450)}},150);setTimeout(()=>{find.disabled=false;find.textContent='⌕  Cari Template'},2600)}
function show(v){let pl=platform(v);$('platform').textContent=pl.toUpperCase();$('name').textContent=pl==='TikTok'?'Trending Beat Motion':pl==='Instagram'?'Reels Cinematic Edit':'Cinematic Beat Edit';$('tpl').textContent=pl==='TikTok'||pl==='Instagram'?'CapCut':'Template DB';$('score').textContent=(88+Math.floor(Math.random()*9))+'%';results.classList.remove('hidden');results.scrollIntoView({behavior:'smooth'})}
$('clear').onclick=()=>{url.value='';url.focus()};url.onkeydown=e=>{if(e.key==='Enter')find.click()};$('use').onclick=()=>msg('Link template akan tersedia setelah backend/API tahap 2 ditambahkan.');
